### ISSUE TITLE
puting a mojs-player document in a iframe causes bugs

### ISSUE THREAD

**Issue by saavor** [mojs/mojs-player#14]
it looks weird
![mojsbug](https://user-images.githubusercontent.com/29069199/27940800-8b5e07f2-62bc-11e7-976e-6c7a7a3ce63d.png)

**Comment by saavor** [comment]
I dont know how to fix it

**Comment by legomushroom** [comment]
Hey @the349, thanks for submitting this issue!

Can you give me more information about the issue you see, from the screenshot I see a blank page with a `mojs-player` at the bottom. You probably have few instances of the `mojs-player` at the same time:

![image](https://user-images.githubusercontent.com/1478800/27940918-5b5e9266-6293-11e7-904d-e7deca00f9fd.png)

**Comment by saavor** [comment]
I don't have more than one instance

**Comment by saavor** [comment]
and I will give you more information about this issue

**Comment by legomushroom** [comment]
@the349 thanks, this will be really helpful!

**Comment by saavor** [comment]
also it only happened in a iframe

**Comment by saavor** [comment]
and I will see if it was just my computer

**Comment by saavor** [comment]
I will check back with you later

**Comment by saavor** [comment]
o and the page kept loading online files from the cdn

**Comment by saavor** [comment]
ok so it was just my computer

**Comment by saavor** [comment]
it did not happen on any of my other computers

**Comment by legomushroom** [comment]
@the349 good to know, thanks. Is the issue appears only on your `Linux` machine? What the issue looked like exactly? Thanks in advance!
