### ISSUE TITLE
Timeline progress not reflected by the player progress indicator.

### ISSUE THREAD

**Issue by loriensleafs** [mojs/mojs-player#15]
Hey,

Let me start by saying this library and workflow tools are unlike anything I've ever seen before in terms of what's available for web animation libraries and you guys should be super proud of what you've accomplished!  Props and thanks, makes me life as a dev much easier.

I'm using this tool in a React project (not sure if this has anything to do with React or not, but it seemed worth mentioning), as well as taking advantage of the mojs player and mojs curve editor.  The curve editor works like magic, no problems there.

The player's start, stop and looping functionality are work as they should, but the progress indicator doesn't move when the animation is playing.  It does however let me change the point in time in the animation if I click on it.

I attached a screenshot of what I'm seeing, and you can see the curve editor progress is accurately represented, but the player progress indicator isn't.

Any thoughts on what's going on here?

Here are some code snippets of my implementation:

	import {Component} from 'react'
	import ReactDOM from 'react-dom'
	import mojs from 'mo-js';
	import MojsPlayer from 'mojs-player';
	import MojsCurveEditor from 'mojs-curve-editor';

	class Animation extends Component {

		componentDidMount() {
			this.stage = ReactDOM.findDOMNode(this.refs.stage);
			this.square = ReactDOM.findDOMNode(this.refs.square);
			this.shadow = ReactDOM.findDOMNode(this.refs.shadow);

			const squareChild = this.square.firstElementChild;

			const FILLS = this.props.inverted
				? [
						'rgba(176,198,216, 0.8)',
						'rgba(0,0,0, 0.3)',
						'rgba(176,198,216, 0.5)',
						'rgba(0,0,0, 0.1)'
					]
				: [
						'rgba(255,255,255, 0.8)',
						'rgba(0,0,0, 0.3)',
						'rgba(255,255,255, 0.5)',
						'rgba(0,0,0, 0.1)'
					];
			const DURATION = 1000;

			const scalePath = mojs.easing.path(
				'M0, 0 C0, 0 16.857142857142854, -5.248486282060085e-15 31.142857142857142, 0 C30.80272108843543, -113.14285714285715 50, -100 50, -100 C50, -100 65.31357300419697, -100.13604825191986 70, -0.2857142857142857 C84.28506645158541, -0.14966603379441404 100, 0 100, 0 '
			);

			const yCurve = new MojsCurveEditor({
				name: 'Y curve editor'
			});
			const angleZCurve = new MojsCurveEditor({
				name: 'Angle Z curve editor'
			});
			const xScale = new MojsCurveEditor({
				name: 'X scale curve editor'
			});
			const yScale = new MojsCurveEditor({
				name: 'Y scale curve editor'
			});
			const square = new mojs.Html({
				el: this.square,
				customProperties: {
					originY: 50,
					draw(el, props) {
						el.style.transformOrigin = `50% ${props.originY}%`;
					}
				},
				y: {
					['0vh']: '-80vh',
					curve: yCurve.getEasing()
				},
				scaleX: {
					1: 1,
					curve: xScale.getEasing()
				},
				scaleY: {
					1: 1,
					curve: yScale.getEasing({
						transform: function(k) {
							return 1 + (1 - scalePath(k)) / 1.3;
						}
					})
				},
				angleZ: {
					[-180]: 0,
					curve: angleZCurve.getEasing()
				},
				duration: DURATION,
				isForce3d: true
			});

			square.rotate = 0;

			this.timeline = new mojs.Timeline({
				onComplete: this._onComplete,
				onStart: this._onStart,
				repeat: 999
			});
			this.timeline.add(square);
			new MojsPlayer({
				add: this.timeline,
				isPlaying: true,
				isRepeat: true
			});
		}

		render() {
			const { small = false, inverted = false } = this.props;

			return (
				<div className={this.props.className} ref={'stage'}>
					<div ref={'square'}>
						<StandaloneLogo />
					</div>
					<div
						ref={'shadow'}
					/>
				</div>
			);
		}
	}

![animationplayertimelineissue](https://user-images.githubusercontent.com/315385/28812596-7092612e-7663-11e7-967d-dc1165ec4413.jpg)

**Comment by legomushroom** [comment]
Hey, Peter!

Thanks a lot for your feedback, it helps me push the tooling forward!

The problem for you is that you set `repeat: 999` on the `timeline` which creates really long progress on the player, so just remove the property from the main timeline and click on the player's repeat button instead, this will make it repeat infinitely (<img src="https://user-images.githubusercontent.com/1478800/28829563-d1661776-7699-11e7-8c45-aab498a57ed2.png" width="40" />). When your animation is ready to go, you can remove the player and switch back to `repeat: 999` on the main timeline.

Hope it helps, let me know!

// @loriensleafs
