### ISSUE TITLE
Mojs Player Latency

### ISSUE THREAD

**Issue by zfrisch** [mojs/mojs-player#17]
Hello! Strangely I'm having an issue with the Mojs Player tracker line being latent. It's only an issue in my Chrome Browser(Version 55.0.2883.87 m, which is the most current). In FF and IE10/Edge it seems to work fine. The error also doesn't seem to show up on CrossBrowserTesting (the site that CodePen uses for Cross Browser Testing). 

I recorded a video to show what I'm talking about: 
https://www.youtube.com/watch?v=K_ib-3OWCuE 

Here's the CodePen : 
http://codepen.io/zfrisch/full/yVwmoW/

Thanks!

**Comment by eltonmesquita** [comment]
Hello @zfrisch . There's a big chance your problem is related to a chrome extension. It's a really common issue. Try to run it in an anonymous window and see if the issue persists.

**Comment by xavierfoucrier** [comment]
Moved to https://github.com/mojs/mojs-player/issues/3.
