### ISSUE TITLE
Add `onToggleHide` callback

### ISSUE THREAD

**Issue by legomushroom** [mojs/mojs-player#2]
Add the `onToggleHide` callback that will be called with a `boolean` indicating the visibility state of the player. This callback should be called after user taps on the button:

![hide button](https://cloud.githubusercontent.com/assets/1478800/20850572/75c148f2-b8a1-11e6-9662-60b024882204.png)

Player's constructor with the callback:
```javascript
new MojsPlayer({
  add: timeline,
  onToggleShow(isHidden) {
    if (isHidden) { // do something when player is invisiblie }
    else { // do something when player is visiblie }
  }
});
```

Please let me know is you are want to help and have any question.

**Comment by dev99problems** [comment]
Hi there
https://github.com/legomushroom/mojs-player/pull/11

**Comment by weisjohn** [comment]
@legomushroom is this ready to close? curious if you still want help on it.

**Comment by legomushroom** [comment]
@weisjohn thanks a lot, this one is merged here: https://github.com/legomushroom/mojs-player/pull/11 , sorry about the confusion.
